name: Angular App Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm test
        env:
          CI: true
  windows-build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.19]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm test
        env:
          CI: true
